name: "CI"

on: push

jobs:
  build:
    name: "ğŸ—ï¸ Gradle build"
    runs-on: ubuntu-18.04
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ§° Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "ğŸ’ª Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "ğŸ—ï¸ Build with Gradle"
        run: "./gradlew build"
  test:
    needs: build
    name: "âœ… Gradle test"
    runs-on: ubuntu-18.04
    steps:
      - name: "ğŸ“¥ Check-out"
        uses: actions/checkout@v2
      - name: "ğŸ§° Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "ğŸ’ª Grant execute permission for gradlew"
        run: "chmod +x gradlew"
      - name: "âœ… Test with Gradle"
        run: "./gradlew test"